name: drug_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  pocketbase: ^0.23.0
  flutter_dotenv: ^5.2.1
  logger: ^2.0.2
  image_picker: ^1.1.2
  http: ^1.4.0
  http_parser: ^4.1.2
  flex_color_scheme: ^8.2.0
  provider: ^6.1.5
  awesome_snackbar_content: ^0.1.7
  flutter_staggered_grid_view: ^0.7.0
  animated_toggle_switch: ^0.8.5  
  permission_handler: ^12.0.1  
  device_info_plus: ^11.5.0
  collection: ^1.19.1
  uuid: ^4.5.1
  intl: ^0.20.2
  awesome_dialog: ^3.2.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/icons/
  uses-material-design: true
